server:
  port: ${PORT_DEV}
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER_DEV}
    password: ${DB_PASS_DEV}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

urlApi: http://localhost:${server.port}
api:
  index: /api
  bus:
    index: /bus
    create: /create
    getall: /list
    delete: /delete/{id}
    edit: /edit
    csvData: /csv
  horario:
    index: /horario
    create: /create
    getall: /list
    getAllBusHorario: /list/filter/buses
    getIdHorario: /one/{id}
  asientos:
    index: /asientos
    create: /comprar
    getAll: /list
    getAsientos: /list/disponibles
