server:
  port: ${PORT_PROD}
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER_PROD}
    password: ${DB_PASS_PROD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  config:
    import: classpath:routes.yml

urlApi: http://localhost:${server.port}