api:
  index: /api
  bus:
    index: /bus
    create: /create
    getall: /list
    delete: /delete/{id}
    edit: /edit
    csvData: /csv
  horario:
    index: /horario
    create: /create
    getall: /list
    getAllBusHorario: /list/filter/buses
    getIdHorario: /one/{id}
  asientos:
    index: /asientos
    create: /comprar
    getAll: /list
    getAsientos: /list/disponibles
